const date=new Date("2023-10-23");
//console.log(date);
//console.log(date.getFullYear());
//console.log(date. getmonth());
//console.log(date.getDay());
//console.log(date.getHours());
//console.log(date.getMinutes());
//console.log(date.getSeconds());
//console.log(date.getMilliseconds());
//console.log(date.getMonth());